// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StajerManager.Models;

#nullable disable

namespace StajerManager.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250919113758_BolumlerBagimsiz")]
    partial class BolumlerBagimsiz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StajerManager.Models.BolumModel", b =>
                {
                    b.Property<int>("BolumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolumID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BolumKodu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EgitimSuresi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EgitimTuru")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Fakulte")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("BolumID");

                    b.HasIndex("BolumAdi")
                        .IsUnique()
                        .HasDatabaseName("IX_Bolumler_BolumAdi");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("StajerManager.Models.DepartmanModel", b =>
                {
                    b.Property<int>("DepartmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmanID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DepartmanAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartmanID");

                    b.HasIndex("DepartmanAdi")
                        .IsUnique()
                        .HasDatabaseName("IX_Departmans_DepartmanAdi");

                    b.ToTable("Departmans");
                });

            modelBuilder.Entity("StajerManager.Models.StajerModel", b =>
                {
                    b.Property<int>("StajerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StajerID"));

                    b.Property<int?>("BolumID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmanID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("UniversiteID")
                        .HasColumnType("int");

                    b.HasKey("StajerID");

                    b.HasIndex("BolumID");

                    b.HasIndex("DepartmanID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Stajers_Email");

                    b.HasIndex("UniversiteID");

                    b.ToTable("Stajers");
                });

            modelBuilder.Entity("StajerManager.Models.UniversiteModel", b =>
                {
                    b.Property<int>("UniversiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UniversiteID"));

                    b.Property<string>("Adres")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostaKodu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Sehir")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UniversiteAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UniversiteID");

                    b.HasIndex("UniversiteAdi")
                        .IsUnique()
                        .HasDatabaseName("IX_Universiteler_UniversiteAdi");

                    b.ToTable("Universiteler");
                });

            modelBuilder.Entity("StajerManager.Models.StajerModel", b =>
                {
                    b.HasOne("StajerManager.Models.BolumModel", "Bolum")
                        .WithMany("Stajers")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StajerManager.Models.DepartmanModel", "Departman")
                        .WithMany("Stajers")
                        .HasForeignKey("DepartmanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StajerManager.Models.UniversiteModel", "Universite")
                        .WithMany("Stajers")
                        .HasForeignKey("UniversiteID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Bolum");

                    b.Navigation("Departman");

                    b.Navigation("Universite");
                });

            modelBuilder.Entity("StajerManager.Models.BolumModel", b =>
                {
                    b.Navigation("Stajers");
                });

            modelBuilder.Entity("StajerManager.Models.DepartmanModel", b =>
                {
                    b.Navigation("Stajers");
                });

            modelBuilder.Entity("StajerManager.Models.UniversiteModel", b =>
                {
                    b.Navigation("Stajers");
                });
#pragma warning restore 612, 618
        }
    }
}
